list_ftp_files.py

This lists the contents of the transfer-complete directory, so curators can match up files and dummy files.

add list_ftp_files.py

---

get_bitstreams_for_package.py

Given a package ID, prints out associated bitstreams

added get_bitstreams_for_package.py

---

FIDO_interpreter.py
JHOVE_output_interpreter.py

Add python code from Christine for interpreting output results from running FIDO and JHOVE

Add python code for interpreting FIDO and JHOVE output

---

nsf_reporting.py

generate report of nsf-sponsored packages

nsf_reporting.py

---

fix_resourcepolicy.py

Fixes archived items where a file is not downloadable, as in https://trello.com/c/4dsPN3kN/319-recurring-files-not-visible-at-public-package-page

Fix resourcepolicy

---

nsf_reporting.py
sync_provenance.py

Sync provenance

---

fix_orcids_in_authorities.py

Update author metadata authorities to format used in https://github.com/datadryad/dryad-repo/pull/1292

add fix_orcids_in_authorities.py

---

jmeter/README.md
jmeter/basicDryadTests.jmx

Add initial version of JMeter tests

---

doi_tool.py
reindex-discovery.py

Update metadata at EZID for items that have had their metadata updated and reindexed.

Reregister updated items

---

fix_orcids_in_authorities.py
fix_resourcepolicy.py
get_bitstreams_for_package.py
nsf_reporting.py
reindex-discovery.py
replace_largefile_bitstream.py
sql_utils.py
sync_provenance.py

I just copied and pasted things, so everything should run as before. There were two versions of dict_from_query, so I changed one to list_from_query.

Refactor common methods into sql_utils

---

fix_orcids_in_authorities.py
fix_resourcepolicy.py
get_affiliations.py
get_bitstreams_for_package.py
nsf_reporting.py
reindex-discovery.py
replace_largefile_bitstream.py
sql_utils.py
sync_provenance.py

First pass at getting institutional affiliations from Crossref for archived packages.

Affiliation report

---

change_email.py
import_pg_dump.sh
sql_utils.py

A convenience script that allows you to update a user’s email address and then reindexes that user’s items.

Change user email

---

aws-tools/backup-sql-solr.sh
database-export.sh
s3_copy_all.py
s3_validate_bitstreams.py

Various scripts to validate and back up things to S3

backup scripts

---

aws-tools/db-rebuild.sh
fix_authors_in_json.py
s3_move_local_bitstreams.py

aws-tools/db-rebuild.sh is a generic version of Ryan's flip/flop scripts for secundus, but isn't really used anymore.
s3_move_local_bitstreams adds an option to move a single bitstream.
fix_authors_in_json.py was a one-time script to fix problems in json_data for manuscripts.

archive these scripts

---

ping-datadryad.sh

Nothing exciting, just copying over a script.

add ping-datadryad script from prod

---

remove_split_bitstreams.py
split_large_bitstream.py

Run `split_large_bitstream.py` to chunk a large file from the assetstore and upload the chunks to the dryad-web-assets bucket. Run `remove_split_bitstreams.py` to remove the chunks when finished.

Split large files

---

change_email.py

A few fixes to improve check_email. Already deployed on prod.

Email update

---

get_affiliations_wrapper.sh

Wrapper file that was on production

Add wrapper

---

get_affiliations.py
get_affiliations_wrapper.sh

Quick fix for the quarterly get_affiliations script

explicitly use --list argument instead of no argument at all

---

dash-migration/dash_stats.sh
dash-migration/sort_dash_stats.sh
dash-migration/transfer_to_dash.sh

These scripts are useful wrappers for processing statistics. They are used with the statistics report produced by https://github.com/datadryad/dryad-repo/pull/1500

Dash migration -- stats processing scripts
